<?php

namespace panix\mod\cart\components\delivery;

use panix\engine\CMS;
use Yii;
use panix\engine\Html;
use yii\base\Component;

class BaseDeliverySystem extends Component
{
    private $_system_name;
    private $_system_name2;

    public function init()
    {
        $this->_system_name = basename(get_class($this->getModel()));
        $this->_system_name2 = basename(get_class($this));
//var_dump($this->_system_name2);die;
        // CMS::dump($this->_system_name);
        // CMS::dump($this->_system_name2);die;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $paymentMethodId
     * @param $data
     */
    public function setSettings($paymentMethodId, $data)
    {
        //echo basename(get_class($this));


        Yii::$app->settings->set($this->getSettingsKey($paymentMethodId), $data);
    }

    /**
     * @param $paymentMethodId
     * @return mixed
     */
    public function getSettings($paymentMethodId)
    {

        return Yii::$app->settings->get($this->getSettingsKey($paymentMethodId));
    }

    /**
     * @param $message string
     */
    public function log($message)
    {
        Yii::info($this->getSettingsKey(basename(get_class($this))) . ': ' . $message);
    }


    public function getSettingsKey($id)
    {
        return $id . '_' . $this->getShortName();
    }

    public function getShortName()
    {
        $reflect = new \ReflectionClass($this);
        return $reflect->getShortName();
    }
}
